#!/bin/sh
#
# Recovery init script
#

# Standard busybox init
/bin/mount -t proc proc /proc
/bin/mount -o remount,rw,noatime /
/bin/mount -t sysfs sysfs /sys
/bin/mount -t devtmpfs dev /dev 2>/dev/null
/bin/hostname -F /etc/hostname
/bin/mount -t tmpfs tmpfs /tmp

# Newer kernel versions can load firmware from /lib/firmware by themselves without help
# However that can fail during boot due to our initrd ramdisk not being mounted in time
# Retry any pending requests
(cd /sys/class/firmware
while [ "$(ls | wc -l)" != "1" ]; do
    for F in *; do
        if [ -d "$F" ]; then
            fw1="/lib/firmware/${F/!//}"
            fw2="$(echo "$fw1" | sed 's/\..*\././')"
            echo 1 > "$F/loading"
            for fw in "$fw1" "$fw2"; do
                if [ -e "$fw" ]; then
                    cat "$fw" > "$F/data"
                    break
                fi
            done
            echo 0 > "$F/loading"
        fi
    done
    sleep 1
done
echo 1 > timeout)

# Rescue shell available on tty2 and tty3
echo 2 >/sys/module/vt/parameters/cur_default
/sbin/getty -L tty2 0 vt100 &
/sbin/getty -L tty3 0 vt100 &
/sbin/getty -L ttyAMA0 115200 vt100 &

# Enable syslog
/etc/init.d/S01logging start > /dev/null



# Recovery should have rebooted
echo Starting resize rootfs...

cat << EOF | fdisk /dev/mmcblk0
d
2
n
p
2
$(cat /sys/block/mmcblk0/mmcblk0p2/start)

w
EOF
resize.f2fs /dev/mmcblk0p2
echo Resize Done.

echo Transfering files.
mount /dev/mmcblk0p1 /boot
mount /dev/mmcblk0p2 /rootfs

rm -rf /boot/*
mv /rootfs/boot/* boot/
sync
umount /rootfs
umount /boot

echo Rebooting.
/usr/bin/recovery -reboot
echo Reboot failed.

sh
